
import React,{useState} from 'react';
import {rpc,errorMessage} from './api.js';
import {Field,Notice,Modal} from './ui.jsx';
import {today,money,priceToMinor,lineTotal} from './utils.js';
const titles={basin:'Bassin',harvest:'Récolte',lot:'Lot',client:'Client',order:'Commande'};
export default function Editor({kind,record={},workspace,data,onClose,onSaved}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[basin,setBasin]=useState(record.basin_id||'');
 const initial=data.items.filter(i=>i.order_id===record.id).map(i=>({lot_id:i.lot_id,quantity_g:i.quantity_g,price:i.unit_price_minor/(workspace.currency==='EUR'?100:1)}));
 const [items,setItems]=useState(initial.length?initial:[{lot_id:'',quantity_g:1000,price:''}]);
 const locked=kind==='lot'&&data.items.some(i=>i.lot_id===record.id);
 const lotOptions=data.lots.filter(l=>l.status==='released');
 const prerequisite=kind==='order'&&(!data.clients.length||!lotOptions.length)?'Ajoutez un client et au moins un lot libéré avant de créer une commande.':['harvest','lot'].includes(kind)&&!data.basins.length?'Ajoutez un bassin avant de continuer.':'';
 const patch=(index,key,value)=>setItems(old=>old.map((item,i)=>i===index?{...item,[key]:value}:item));
 async function submit(e){e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{
 if(record.id)v.id=record.id;
 if(kind==='basin'){v.active=v.active==='true';v.volume_l=Number(v.volume_l);}
 if(kind==='harvest')v.fresh_weight_g=Number(v.fresh_weight_g);
 if(kind==='lot'){v.dry_weight_g=Number(v.dry_weight_g);if(locked)for(const key of ['reference','basin_id','harvest_id','produced_on'])v[key]=record[key];}
 if(kind==='order')await rpc('sp_save_order',{p_workspace:workspace.id,p_order:v,p_items:items.map(i=>({lot_id:i.lot_id,quantity_g:Number(i.quantity_g),unit_price_minor:priceToMinor(i.price,workspace.currency)})),p_expected_version:record.version||null});
 else await rpc('sp_save_record',{p_workspace:workspace.id,p_kind:kind,p_record:v,p_expected_version:record.version||null});
 onSaved();
 }catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
 const basinField=<Field label="Bassin"><select name="basin_id" required disabled={locked} value={basin} onChange={e=>setBasin(e.target.value)}><option value="">Choisir un bassin</option>{data.basins.map(b=><option key={b.id} value={b.id}>{b.name}{b.active?'':' (inactif)'}</option>)}</select></Field>;
 return <Modal title={(record.id?'Modifier : ':'Ajouter : ')+titles[kind]} onClose={()=>!busy&&onClose()}><Notice>{error||prerequisite}</Notice><form onSubmit={submit}>
 {kind==='basin'&&<><div className="form-grid"><Field label="Nom du bassin" name="name" required maxLength={120} defaultValue={record.name}/><Field label="Volume (litres)" name="volume_l" type="number" min="0.01" step="0.01" required defaultValue={record.volume_l}/></div><Field label="État"><select name="active" defaultValue={String(record.active??true)}><option value="true">En activité</option><option value="false">Inactif</option></select></Field></>}
 {kind==='harvest'&&<><div className="form-grid">{basinField}<Field label="Date de récolte" name="harvested_on" type="date" required defaultValue={record.harvested_on||today()}/></div><Field label="Masse fraîche (grammes)" name="fresh_weight_g" type="number" min="1" max="100000000" step="1" required defaultValue={record.fresh_weight_g}/></>}
 {kind==='lot'&&<>{locked&&<p className="muted">La provenance est protégée car ce lot est lié à une commande.</p>}<div className="form-grid"><Field label="Référence du lot" name="reference" required maxLength={120} disabled={locked} defaultValue={record.reference}/>{basinField}<Field label="Récolte d’origine (facultatif)"><select key={basin} name="harvest_id" disabled={locked} defaultValue={record.basin_id===basin?record.harvest_id||'':''}><option value="">Non renseignée</option>{data.harvests.filter(h=>h.basin_id===basin).map(h=><option key={h.id} value={h.id}>{h.harvested_on} — {h.fresh_weight_g} g</option>)}</select></Field><Field label="Date de production" name="produced_on" type="date" disabled={locked} required defaultValue={record.produced_on||today()}/><Field label="Masse sèche totale (grammes)" name="dry_weight_g" type="number" min="1" max="100000000" step="1" required defaultValue={record.dry_weight_g}/><Field label="Statut qualité"><select name="status" defaultValue={record.status||'analysis'}><option value="analysis">En analyse</option><option value="released">Libéré</option><option value="blocked">Bloqué</option></select></Field></div><Field label="Résultats et observations qualité"><textarea name="analysis_notes" maxLength={5000} defaultValue={record.analysis_notes}/></Field><div className="form-grid"><Field label="Référence du certificat bio (facultatif)" name="certificate_reference" maxLength={200} defaultValue={record.certificate_reference}/><Field label="Fin de validité du certificat" name="certificate_expires_on" type="date" defaultValue={record.certificate_expires_on||''}/></div><p className="muted">Une référence saisie ne constitue pas une vérification de certification.</p></>}
 {kind==='client'&&<><Field label="Nom / raison sociale" name="name" required maxLength={160} defaultValue={record.name}/><div className="form-grid"><Field label="Adresse e-mail" name="email" type="email" maxLength={200} defaultValue={record.email}/><Field label="Téléphone" name="phone" maxLength={80} defaultValue={record.phone}/></div><Field label="Adresse"><textarea name="address" maxLength={2000} defaultValue={record.address}/></Field></>}
 {kind==='order'&&<><div className="form-grid"><Field label="Client"><select name="client_id" required defaultValue={record.client_id||''}><option value="">Choisir un client</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Date de commande" name="ordered_on" type="date" required defaultValue={record.ordered_on||today()}/></div><p className="muted">Les prix sont par kilogramme. Le stock sera réservé à la confirmation.</p>{items.map((item,i)=><div className="order-line" key={i}><Field label={'Lot '+(i+1)}><select required value={item.lot_id} onChange={e=>patch(i,'lot_id',e.target.value)}><option value="">Choisir un lot</option>{lotOptions.map(l=><option key={l.id} value={l.id}>{l.reference} — {l.sellable_g} g disponibles</option>)}</select></Field><Field label="Quantité (g)" type="number" min="1" max="100000000" step="1" required value={item.quantity_g} onChange={e=>patch(i,'quantity_g',e.target.value)}/><Field label={'Prix/kg ('+workspace.currency+')'} type="number" min="0" step={workspace.currency==='EUR'?'0.01':'1'} required value={item.price} onChange={e=>patch(i,'price',e.target.value)}/><button type="button" disabled={items.length===1} onClick={()=>setItems(items.filter((_,j)=>j!==i))} aria-label={'Retirer la ligne '+(i+1)}>✕</button></div>)}<div className="spread"><button type="button" disabled={items.length>=50} onClick={()=>setItems([...items,{lot_id:'',quantity_g:1000,price:''}])}>Ajouter une ligne</button><strong>{money(items.reduce((n,i)=>n+lineTotal(i.quantity_g,Math.round(Number(i.price||0)*(workspace.currency==='EUR'?100:1))),0),workspace.currency)}</strong></div></>}
 {kind!=='lot'&&<Field label="Notes"><textarea name="notes" maxLength={5000} defaultValue={record.notes}/></Field>}
 <footer className="form-actions"><button type="button" disabled={busy} onClick={onClose}>Annuler</button><button className="primary" disabled={busy||!!prerequisite}>{busy?'Enregistrement…':'Enregistrer'}</button></footer></form></Modal>;
}
