
import React,{useEffect,useRef,useState} from 'react';
import {db,rpc,table,errorMessage} from './api.js';
import {Badge,DataTable,Field,Modal,Notice} from './ui.jsx';
import {kg,money,date,today,csv,download,labels} from './utils.js';
import Editor from './Editor.jsx';
import Team from './Team.jsx';
const pages=[['overview','Vue d’ensemble','◉'],['basins','Bassins','▱'],['harvests','Récoltes','↗'],['lots','Lots & stock','▦'],['clients','Clients','♧'],['orders','Commandes','▤'],['team','Équipe','◎'],['events','Historique','◷'],['settings','Paramètres','⚙']];
const definitions={basins:['basin','un bassin'],harvests:['harvest','une récolte'],lots:['lot','un lot'],clients:['client','un client'],orders:['order','une commande']};
const emptyData={basins:[],harvests:[],lots:[],clients:[],orders:[],items:[],events:[]};
export default function Platform({workspace,user,spaces,onSelect,onAdd,reloadSpaces}){
 const [page,setPage]=useState('overview'),[data,setData]=useState(emptyData),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[mobile,setMobile]=useState(false),[updated,setUpdated]=useState(null),[status,setStatus]=useState('');
 const request=useRef(0),abort=useRef(null),mounted=useRef(true);
 const edit=['owner','manager'].includes(workspace.role);
 async function refresh(){const seq=++request.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setRefreshing(true);
 try{const keys=['basins','harvests','lots','clients','orders','items',...(edit?['events']:[])],names={basins:'sp_basins',harvests:'sp_harvests',lots:'sp_lot_stock',clients:'sp_clients',orders:'sp_order_totals',items:'sp_order_items',events:'sp_events'};const values=await Promise.all(keys.map(k=>table(names[k],workspace.id,controller.signal)));if(mounted.current&&seq===request.current){setData({...emptyData,...Object.fromEntries(keys.map((k,i)=>[k,values[i]]))});setLoaded(true);setError('');setUpdated(new Date());}}
 catch(e){if(mounted.current&&seq===request.current&&!controller.signal.aborted)setError(errorMessage(e));}
 finally{if(mounted.current&&seq===request.current)setRefreshing(false);}}
 useEffect(()=>{mounted.current=true;refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh();},60000);return()=>{mounted.current=false;request.current++;abort.current?.abort();clearInterval(timer);};},[workspace.id,edit]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn();if(mounted.current)await refresh();}catch(e){if(mounted.current)setError(errorMessage(e));}finally{if(mounted.current)setBusy(false);}}
 const find=(key,id,prop='name')=>data[key].find(r=>r.id===id)?.[prop]||'—';
 const switchPage=p=>{setPage(p);setStatus('');setMobile(false);};
 const remove=(kind,r)=>run(async()=>{if(!window.confirm('Supprimer définitivement cet élément ? Les éléments liés à d’autres données sont protégés.'))return;await rpc('sp_delete_record',{p_workspace:workspace.id,p_kind:kind,p_id:r.id,p_expected_version:r.version});});
 const transition=(r,s)=>run(async()=>{const message=s==='confirmed'?'Confirmer cette commande et réserver le stock ?':s==='shipped'?'Marquer cette commande comme expédiée ? Cette action est définitive.':'Annuler cette commande et libérer les éventuelles réservations ?';if(!window.confirm(message))return;await rpc('sp_transition_order',{p_workspace:workspace.id,p_order:r.id,p_status:s,p_expected_version:r.version});});
 const columns={
 basins:[{key:'name',label:'Bassin'},{key:'volume_l',label:'Volume',render:r=>Number(r.volume_l).toLocaleString('fr-FR')+' L'},{key:'active',label:'État',render:r=>r.active?'En activité':'Inactif'}],
 harvests:[{key:'harvested_on',label:'Date',render:r=>date(r.harvested_on)},{key:'basin_id',label:'Bassin',render:r=>find('basins',r.basin_id),search:r=>find('basins',r.basin_id)},{key:'fresh_weight_g',label:'Masse fraîche',render:r=>kg(r.fresh_weight_g)}],
 lots:[{key:'reference',label:'Référence'},{key:'produced_on',label:'Production',render:r=>date(r.produced_on)},{key:'status',label:'Qualité',render:r=><Badge value={r.status}/>,search:r=>labels[r.status]},{key:'physical_g',label:'Stock physique',render:r=>kg(r.physical_g)},{key:'reserved_g',label:'Réservé',render:r=>kg(r.reserved_g)},{key:'sellable_g',label:'Disponible à la vente',render:r=><strong>{kg(r.sellable_g)}</strong>}],
 clients:[{key:'name',label:'Client'},{key:'email',label:'E-mail'},{key:'phone',label:'Téléphone'}],
 orders:[{key:'number',label:'Numéro'},{key:'client_id',label:'Client',render:r=>find('clients',r.client_id),search:r=>find('clients',r.client_id)},{key:'ordered_on',label:'Date',render:r=>date(r.ordered_on)},{key:'status',label:'Statut',render:r=><Badge value={r.status}/>,search:r=>labels[r.status]},{key:'total_minor',label:'Montant',render:r=>money(r.total_minor,r.currency)}]
 };
 const actions=r=><>{['lots','orders'].includes(page)&&<button onClick={()=>setDetail({page,record:r})}>Détails</button>}{edit&&(page!=='orders'||r.status==='draft')&&<><button disabled={busy} onClick={()=>setEditor({kind:definitions[page][0],record:r})}>Modifier</button><button disabled={busy} className="danger" onClick={()=>remove(definitions[page][0],r)}>Supprimer</button></>}{edit&&page==='orders'&&r.status==='draft'&&<button disabled={busy} onClick={()=>transition(r,'confirmed')}>Confirmer</button>}{edit&&page==='orders'&&r.status==='confirmed'&&<button disabled={busy} onClick={()=>transition(r,'shipped')}>Expédier</button>}{edit&&page==='orders'&&['draft','confirmed'].includes(r.status)&&<button disabled={busy} onClick={()=>transition(r,'cancelled')}>Annuler</button>}</>;
 const exportCsv=()=>{const keys=Object.keys(data[page][0]||{});download('spiruline-'+page+'-'+today()+'.csv',csv([keys,...data[page].map(r=>keys.map(k=>r[k]))]),'text/csv;charset=utf-8');};
 const currentTitle=pages.find(p=>p[0]===page)?.[1];
 const rows=(data[page]||[]).filter(r=>!status||r.status===status).slice().sort((a,b)=>(b.created_at||'').localeCompare(a.created_at||''));
 return <div className="app"><button className="mobile-toggle" aria-label="Ouvrir le menu" onClick={()=>setMobile(!mobile)}>☰</button>{mobile&&<button className="scrim" aria-label="Fermer le menu" onClick={()=>setMobile(false)}/>}<aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><b className="symbol">S</b><div>SPIRULINE<small>PLATFORM</small></div></div><Field label="Votre entreprise"><select value={workspace.id} onChange={e=>onSelect(e.target.value)}>{spaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><button className="add-space" onClick={onAdd}>＋ Créer ou rejoindre un espace</button><p className="nav-label">ESPACE DE GESTION</p><nav>{pages.filter(([p])=>p!=='events'||edit).map(([p,label,icon])=><button key={p} onClick={()=>switchPage(p)} className={page===p?'active':''} aria-current={page===p?'page':undefined}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><Badge value={workspace.role}/><small>{user.email}</small><button onClick={()=>db.auth.signOut({scope:'local'})}>Se déconnecter</button></div></aside>
 <main className="main"><header className="topbar"><span>{workspace.name}</span><span className="session"><i/> Session active</span></header><div className="content"><div className="page-heading"><div><p className="eyebrow">VOTRE ACTIVITÉ, EN CLAIR</p><h1>{currentTitle}</h1><p className="muted">{page==='overview'?'De vos bassins à vos clients, gardez le fil de votre production.':'Les données de votre entreprise, partagées avec votre équipe.'}</p></div><button disabled={refreshing} onClick={refresh}>{refreshing?'Actualisation…':'↻ Actualiser'}</button></div><Notice>{error}</Notice>{updated&&<small className="last-update">Dernière actualisation : {updated.toLocaleTimeString('fr-FR')} · Actualisation automatique chaque minute</small>}
 {!loaded?<section className="panel" role="status">{error?'Les données n’ont pas pu être chargées. Réessayez avec Actualiser.':'Chargement des données…'}</section>:<>
 {page==='overview'&&<Overview data={data} workspace={workspace} go={switchPage}/>}
 {definitions[page]&&<section className="panel"><div className="spread"><h2>{currentTitle}</h2><div className="row-actions"><button onClick={exportCsv} disabled={!data[page].length}>Exporter CSV</button>{edit&&<button className="primary" onClick={()=>setEditor({kind:definitions[page][0],record:{}})}>＋ Ajouter {definitions[page][1]}</button>}</div></div>{['lots','orders'].includes(page)&&<Field label="Filtrer par statut"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option>{(page==='lots'?['analysis','released','blocked']:['draft','confirmed','shipped','cancelled']).map(s=><option value={s} key={s}>{labels[s]}</option>)}</select></Field>}<DataTable key={page+status} rows={rows} columns={columns[page]} actions={actions} empty={'Aucun élément. '+(edit?'Commencez avec le bouton Ajouter.':'Votre équipe n’a pas encore ajouté de données.')}/></section>}
 {page==='team'&&<Team workspace={workspace} run={run}/>}
 {page==='events'&&edit&&<section className="panel"><h2>Journal des modifications</h2><DataTable rows={[...data.events].sort((a,b)=>Number(b.id)-Number(a.id))} columns={[{key:'created_at',label:'Date',render:r=>date(r.created_at)+' '+new Date(r.created_at).toLocaleTimeString('fr-FR')},{key:'entity_type',label:'Élément'},{key:'action',label:'Action'},{key:'actor_id',label:'Auteur',render:r=>r.actor_id===user.id?'Vous':r.actor_id||'—'}]} actions={r=><button onClick={()=>setDetail({page:'events',record:r})}>Voir</button>}/></section>}
 {page==='settings'&&<section className="panel settings"><h2>Paramètres de l’entreprise</h2><form onSubmit={e=>{e.preventDefault();const v=new FormData(e.currentTarget);run(async()=>{await rpc('sp_update_workspace',{p_workspace:workspace.id,p_name:v.get('name'),p_currency:data.orders.length?workspace.currency:v.get('currency'),p_expected_version:workspace.version});await reloadSpaces(workspace.id);});}}><Field label="Nom de l’entreprise" name="name" required maxLength={120} defaultValue={workspace.name} disabled={workspace.role!=='owner'}/><Field label="Devise"><select name="currency" defaultValue={workspace.currency} disabled={workspace.role!=='owner'||!!data.orders.length}><option value="EUR">Euro — EUR</option><option value="XOF">Franc CFA — XOF</option></select></Field><p className="muted">La devise est verrouillée dès la première commande. Les montants ne constituent pas des factures fiscales.</p>{workspace.role==='owner'&&<button disabled={busy} className="primary">Enregistrer</button>}</form><hr/><h3>Exporter les données consultables</h3><p>L’export JSON contient les données chargées de cet espace. Il sert à la consultation et ne permet pas une restauration automatique.</p><button onClick={()=>download('spiruline-'+today()+'.json',JSON.stringify({exported_at:new Date().toISOString(),workspace,data},null,2),'application/json')}>Télécharger l’export JSON</button></section>}
 </>}
 </div></main>{editor&&<Editor key={editor.kind+(editor.record.id||'new')} {...editor} workspace={workspace} data={data} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);refresh();}}/>}
 {detail&&<Details detail={detail} data={data} find={find} onClose={()=>setDetail(null)}/>}
 </div>;
}
function Overview({data,workspace,go}){
 const stock=data.lots.reduce((n,l)=>n+Number(l.sellable_g),0),reserved=data.lots.reduce((n,l)=>n+Number(l.reserved_g),0),pending=data.orders.filter(o=>o.status==='confirmed'),sales=data.orders.filter(o=>o.status==='shipped').reduce((n,o)=>n+Number(o.total_minor),0);
 const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const key=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');return {key,label:d.toLocaleDateString('fr-FR',{month:'short'}),value:data.lots.filter(l=>l.produced_on.startsWith(key)).reduce((n,l)=>n+Number(l.dry_weight_g),0)};});const max=Math.max(1,...months.map(m=>m.value));
 return <><div className="stats">{[['Stock disponible',kg(stock),'Lots libérés, hors réservations'],['Stock réservé',kg(reserved),pending.length+' commande(s) à expédier'],['Ventes expédiées',money(sales,workspace.currency),'Cumul des commandes expédiées'],['Bassins actifs',data.basins.filter(b=>b.active).length,data.basins.length+' bassin(s) au total']].map(([label,value,sub])=><article className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="spread"><h2>Production sèche</h2><span className="muted">6 derniers mois</span></div><div className="chart" role="img" aria-label={'Production sèche : '+months.map(m=>m.label+' '+kg(m.value)).join(', ')}>{months.map(m=><div className="chart-column" key={m.key}><small>{kg(m.value)}</small><div className="bar-track"><div style={{height:(m.value/max*100)+'%'}}/></div><span>{m.label}</span></div>)}</div></section><section className="panel"><h2>À suivre aujourd’hui</h2><div className="task"><div><strong>{data.lots.filter(l=>l.status==='analysis').length} lots en analyse</strong><small>Contrôlez la qualité avant libération.</small></div><button onClick={()=>go('lots')}>Voir</button></div><div className="task"><div><strong>{pending.length} commandes à expédier</strong><small>Le stock est déjà réservé.</small></div><button onClick={()=>go('orders')}>Voir</button></div><div className="task"><div><strong>{data.lots.filter(l=>l.status==='blocked').length} lots bloqués</strong><small>Exclus du stock disponible à la vente.</small></div><button onClick={()=>go('lots')}>Voir</button></div></section></div><section className="panel welcome"><div><p className="eyebrow">UNE TRAÇABILITÉ À CHAQUE ÉTAPE</p><h2>Commencez par vos bassins.</h2><p>Enregistrez une récolte, créez un lot, puis préparez votre première commande.</p></div><button className="primary" onClick={()=>go('basins')}>Gérer mes bassins →</button></section></>;
}
function Details({detail,data,find,onClose}){
 const {page,record:r}=detail;
 return <Modal title={page==='lots'?'Lot '+r.reference:page==='orders'?'Commande '+r.number:'Détail de la modification'} onClose={onClose}>{page==='events'?<pre>{JSON.stringify(r.changes,null,2)}</pre>:page==='lots'?<><Badge value={r.status}/><dl><dt>Bassin</dt><dd>{find('basins',r.basin_id)}</dd><dt>Production</dt><dd>{date(r.produced_on)}</dd><dt>Masse sèche totale</dt><dd>{kg(r.dry_weight_g)}</dd><dt>Physique / réservé / expédié</dt><dd>{kg(r.physical_g)} / {kg(r.reserved_g)} / {kg(r.shipped_g)}</dd><dt>Analyses</dt><dd>{r.analysis_notes||'Non renseignées'}</dd><dt>Certificat bio déclaré</dt><dd>{r.certificate_reference||'Non renseigné'} {r.certificate_expires_on?'· échéance '+date(r.certificate_expires_on):''}</dd></dl><h3>Commandes liées</h3><DataTable rows={data.items.filter(i=>i.lot_id===r.id)} columns={[{key:'order_id',label:'Commande',render:i=>find('orders',i.order_id,'number')},{key:'quantity_g',label:'Quantité',render:i=>kg(i.quantity_g)}]}/></>:<><Badge value={r.status}/><p><strong>{find('clients',r.client_id)}</strong> · {date(r.ordered_on)}</p><DataTable rows={data.items.filter(i=>i.order_id===r.id)} columns={[{key:'lot_id',label:'Lot',render:i=>find('lots',i.lot_id,'reference')},{key:'quantity_g',label:'Quantité',render:i=>kg(i.quantity_g)},{key:'unit_price_minor',label:'Prix / kg',render:i=>money(i.unit_price_minor,r.currency)},{key:'line_total_minor',label:'Montant',render:i=>money(i.line_total_minor,r.currency)}]}/><p className="total">Total : {money(r.total_minor,r.currency)}</p><p>{r.notes}</p><small>Document de suivi commercial, sans calcul de TVA ni valeur de facture fiscale.</small></>}</Modal>;
}
