
import React,{useEffect,useState} from 'react';
import {rpc,errorMessage,rootUrl} from './api.js';
import {Field,Notice,Badge,DataTable} from './ui.jsx';
import {date,labels} from './utils.js';
export default function Team({workspace,run}){
 const [members,setMembers]=useState([]),[invites,setInvites]=useState([]),[error,setError]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const owner=workspace.role==='owner';
 const load=async()=>{const [m,i]=await Promise.all([rpc('sp_list_members',{p_workspace:workspace.id}),owner?rpc('sp_list_invitations',{p_workspace:workspace.id}):Promise.resolve([])]);setMembers(m);setInvites(i);};
 useEffect(()=>{let alive=true;Promise.all([rpc('sp_list_members',{p_workspace:workspace.id}),owner?rpc('sp_list_invitations',{p_workspace:workspace.id}):Promise.resolve([])]).then(([m,i])=>{if(alive){setMembers(m);setInvites(i);}}).catch(e=>alive&&setError(errorMessage(e))).finally(()=>alive&&setLoading(false));return()=>{alive=false;};},[workspace.id,owner]);
 const mutate=(name,args,message)=>run(async()=>{if(!window.confirm(message))return;await rpc(name,{p_workspace:workspace.id,...args});await load();});
 return <><Notice>{error}</Notice><section className="panel"><h2>Membres de l’entreprise</h2><p className="muted">Les gestionnaires suivent la production et les ventes. Les lecteurs consultent les données.</p>{loading?<p role="status">Chargement de l’équipe…</p>:<DataTable rows={members} columns={[{key:'email',label:'Adresse e-mail'},{key:'role',label:'Rôle',render:r=><Badge value={r.role}/>},{key:'joined_at',label:'Depuis',render:r=>date(r.joined_at)}]} actions={owner?r=>r.role==='owner'?null:<><button onClick={()=>mutate('sp_set_member_role',{p_user:r.user_id,p_role:r.role==='viewer'?'manager':'viewer',p_expected_role:r.role},'Changer le rôle de '+r.email+' en '+labels[r.role==='viewer'?'manager':'viewer']+' ?')}>Changer le rôle</button><button className="danger" onClick={()=>mutate('sp_remove_member',{p_user:r.user_id,p_expected_role:r.role},'Retirer immédiatement l’accès de '+r.email+' ?')}>Retirer</button></>:null}/>}</section>
 {owner&&<section className="panel"><h2>Inviter un membre</h2><p>Créez un lien valable 7 jours, réservé à l’adresse indiquée. Partagez-le vous-même avec votre collègue.</p><form onSubmit={async e=>{e.preventDefault();const v=new FormData(e.currentTarget);setBusy(true);setError('');try{const result=await rpc('sp_create_invitation',{p_workspace:workspace.id,p_email:v.get('email'),p_role:v.get('role')});setLink(rootUrl()+'#invite='+result.token);await load();}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}}><div className="form-grid"><Field label="Adresse e-mail du membre" name="email" type="email" required maxLength={200}/><Field label="Rôle"><select name="role"><option value="viewer">Lecture seule</option><option value="manager">Gestionnaire</option></select></Field></div><button className="primary" disabled={busy}>{busy?'Création…':'Créer un lien d’invitation'}</button></form>{link&&<div className="notice success"><Field label="Lien à partager"><input readOnly value={link} onFocus={e=>e.target.select()}/></Field><small>Aucun e-mail n’est envoyé automatiquement.</small></div>}
 <h3>Invitations</h3><DataTable rows={invites} columns={[{key:'email',label:'Destinataire'},{key:'role',label:'Rôle',render:r=><Badge value={r.role}/>},{key:'expires_at',label:'Expiration',render:r=>date(r.expires_at)},{key:'state',label:'État',render:r=>r.accepted_at?'Acceptée':r.revoked_at?'Révoquée':new Date(r.expires_at)<new Date()?'Expirée':'En attente'}]} actions={r=>!r.accepted_at&&!r.revoked_at&&new Date(r.expires_at)>new Date()?<button onClick={()=>mutate('sp_revoke_invitation',{p_invitation:r.id},'Révoquer cette invitation ?')}>Révoquer</button>:null}/></section>}</>;
}
